"""
    FEM2D_P1{T}

Discretization tag for `geometric_fem2d_P1` and `fem2d_P1`. You will rarely
construct this directly — call those functions instead.

Fields: `K::Matrix{T}` (the input triangulation, 3n × 2) and `L::Int`
(number of multigrid levels recorded for plotting/dispatch; informational).
"""
struct FEM2D_P1{T}
    K::Matrix{T}
    L::Int
end

MultiGridBarrier.amg_dim(::FEM2D_P1) = 2

function plot(M::Geometry{T, Matrix{T}, Vector{T}, <:Any, <:Any, <:Any, <:Any, FEM2D_P1{T}}, z::Vector{T}; kwargs...) where {T}
    x = M.x[:,1]
    y = M.x[:,2]
    N = size(x,1) ÷ 3
    S = reshape(0:(3*N-1), 3, N)'
    plot_trisurf(x, y, z, triangles=S; kwargs...)
end

"""
    geometric_fem2d_P1(::Type{T}=Float64; K, L=2) -> Geometry

Construct a 2D FEM geometry on the triangulation `K` with **P1**
(piecewise-linear) elements and a multigrid hierarchy generated by
`L − 1` levels of 4-way midpoint subdivision (standard geometric
multigrid for triangles). The result is passed to `amgb`.

This is the geometric counterpart of `fem2d_P1`; the two produce
matching solutions on identical fine meshes.

# Arguments

- `K::Matrix{T}` (size `3n × 2`): the **coarsest** triangulation. Each
  three consecutive rows give one triangle's three vertex coordinates
  `(x, y)`. Triangles share vertices by coincident coordinates. Vertex
  order within a triangle is unconstrained.

- `L::Int`: number of multigrid levels. The fine mesh has `n · 4^(L-1)`
  triangles. Default `2`.

# Example
```julia
K = Float64[-1 -1;  1 -1; -1  1;
             1 -1;  1  1; -1  1]
geom = geometric_fem2d_P1(; K=K, L=4)        # 32 fine triangles
sol  = amgb(geom; p=1.5)
```
"""
function geometric_fem2d_P1(::Type{T}=Float64;
                  K = T[-1 -1; 1 -1; -1 1; 1 -1; 1 1; -1 1],
                  L::Int=2, rest...) where {T}
    K_T = collect(T, K)
    size(K_T, 1) % 3 == 0 ||
        throw(ArgumentError("K must have 3 rows per triangle (3n × 2)"))
    L >= 1 || throw(ArgumentError("L must be ≥ 1"))

    nn = size(K_T, 1) ÷ 3   # number of coarse triangles

    # Reference data for one P1 triangle:
    #   R_K        : 3×3 identity (barycentric → mesh; R_K * K_local = corner xy).
    #   R_refine   : 12×3, from parent corners to 4 children (each 3 corners).
    #   R_coarsen  : 3×12, picks the parent corners back from one child each.
    R_K       = sparse(T(1) * I, 3, 3)
    R_refine  = _p1_reference_refine(T)
    R_coarsen = _p1_reference_coarsen(T)

    # ---------------- Mesh hierarchy ----------------
    x       = Vector{Matrix{T}}(undef, L)
    refine  = Vector{SparseMatrixCSC{T,Int}}(undef, L)
    coarsen = Vector{SparseMatrixCSC{T,Int}}(undef, L)

    x[1] = blockdiag([R_K for _ in 1:nn]...) * K_T   # 3*nn × 2

    for l in 1:L-1
        n_tri      = nn * 4^(l - 1)
        refine[l]  = blockdiag([R_refine  for _ in 1:n_tri]...)
        coarsen[l] = blockdiag([R_coarsen for _ in 1:n_tri]...)
        x[l + 1]   = refine[l] * x[l]
    end

    # ---------------- Operators at fine level ----------------
    n_doubled = size(x[L], 1)
    N_fine    = n_doubled ÷ 3

    id    = sparse(one(T) * I, n_doubled, n_doubled)
    dx_op, dy_op, w = _p1_assemble_operators(x[L], N_fine, T)

    refine[L]  = id
    coarsen[L] = id

    # ---------------- Subspaces ----------------
    sub_dirichlet = Vector{SparseMatrixCSC{T,Int}}(undef, L)
    sub_full      = Vector{SparseMatrixCSC{T,Int}}(undef, L)
    sub_uniform   = Vector{SparseMatrixCSC{T,Int}}(undef, L)
    for l in 1:L
        sub_dirichlet[l] = _continuous_p1(x[l])
        sub_full[l]      = sparse(one(T) * I, size(x[l], 1), size(x[l], 1))
        sub_uniform[l]   = sparse(ones(T, size(x[l], 1), 1))
    end

    subspaces = Dict{Symbol, Vector{SparseMatrixCSC{T,Int}}}(
        :dirichlet => sub_dirichlet,
        :full      => sub_full,
        :uniform   => sub_uniform,
    )
    operators = Dict{Symbol, SparseMatrixCSC{T,Int}}(
        :id => id, :dx => dx_op, :dy => dy_op,
    )

    disc = FEM2D_P1{T}(K_T, L)
    return Geometry{T, Matrix{T}, Vector{T}, SparseMatrixCSC{T,Int}, FEM2D_P1{T}}(
        disc, x[L], w, subspaces, operators, refine, coarsen
    )
end

"""
    geometric_fem2d_P1_solve(::Type{T}=Float64; rest...) -> AMGBSOL

Solve a 2D Dirichlet variational problem with P1 triangular elements.
Equivalent to `amgb(geometric_fem2d_P1(T; rest...); rest...)`: keyword arguments are
forwarded to both `geometric_fem2d_P1` (mesh kwargs `K`, `L`) and `amgb` (solver
kwargs `p`, `f`, `g`, `verbose`, …).

# Example
```julia
sol = geometric_fem2d_P1_solve(L=4, p=1.5)        # default unit-square K
```

See `amgb` for the full set of solver kwargs and the variational
formulation (default p-Laplace).
"""
geometric_fem2d_P1_solve(::Type{T}=Float64; rest...) where {T} = amgb(geometric_fem2d_P1(T; rest...); rest...)

# ============================================================================
# Helpers
# ============================================================================

# Refine map per parent triangle: 12×3.
# Children (in order):
#   0: (P1, M12, M31)  — around corner 1
#   1: (M12, P2, M23)  — around corner 2
#   2: (M31, M23, P3)  — around corner 3
#   3: (M12, M23, M31) — central inverted child
function _p1_reference_refine(::Type{T}) where {T}
    sparse(T[
        1.0 0.0 0.0;     # child 0, corner 1 = P1
        0.5 0.5 0.0;     # child 0, corner 2 = M12
        0.5 0.0 0.5;     # child 0, corner 3 = M31
        0.5 0.5 0.0;     # child 1, corner 1 = M12
        0.0 1.0 0.0;     # child 1, corner 2 = P2
        0.0 0.5 0.5;     # child 1, corner 3 = M23
        0.5 0.0 0.5;     # child 2, corner 1 = M31
        0.0 0.5 0.5;     # child 2, corner 2 = M23
        0.0 0.0 1.0;     # child 2, corner 3 = P3
        0.5 0.5 0.0;     # child 3, corner 1 = M12
        0.0 0.5 0.5;     # child 3, corner 2 = M23
        0.5 0.0 0.5;     # child 3, corner 3 = M31
    ])
end

# Coarsen: pick parent corners back from one child each.
#   P1 lives at child 0 corner 1 (fine row 1).
#   P2 lives at child 1 corner 2 (fine row 5).
#   P3 lives at child 2 corner 3 (fine row 9).
function _p1_reference_coarsen(::Type{T}) where {T}
    rows = [1, 2, 3]
    cols = [1, 5, 9]
    sparse(rows, cols, ones(T, 3), 3, 12)
end

# Per-element dx, dy (block-diagonal 3×3 per triangle) and lumped vertex
# quadrature weight (area / 3 per node).
function _p1_assemble_operators(x_fine::Matrix{T}, N::Int, ::Type{T}) where {T}
    rows_dx = Vector{Int}(undef, 9*N); cols_dx = Vector{Int}(undef, 9*N); vals_dx = Vector{T}(undef, 9*N)
    rows_dy = Vector{Int}(undef, 9*N); cols_dy = Vector{Int}(undef, 9*N); vals_dy = Vector{T}(undef, 9*N)
    w = zeros(T, 3*N)
    @inbounds for k in 1:N
        i1, i2, i3 = 3*(k-1) + 1, 3*(k-1) + 2, 3*(k-1) + 3
        x1, y1 = x_fine[i1, 1], x_fine[i1, 2]
        x2, y2 = x_fine[i2, 1], x_fine[i2, 2]
        x3, y3 = x_fine[i3, 1], x_fine[i3, 2]
        det2 = (x2 - x1)*(y3 - y1) - (x3 - x1)*(y2 - y1)   # signed 2·area
        area = abs(det2) / 2
        # ∂φ_j/∂x = b_j / det2, where b_j = y_{j+1} - y_{j+2} cyclically.
        # ∂φ_j/∂y = c_j / det2.
        b = (y2 - y3, y3 - y1, y1 - y2)
        c = (x3 - x2, x1 - x3, x2 - x1)
        for i in 1:3, j in 1:3
            idx = 9*(k-1) + 3*(i-1) + j
            rows_dx[idx] = 3*(k-1) + i
            cols_dx[idx] = 3*(k-1) + j
            vals_dx[idx] = b[j] / det2
            rows_dy[idx] = 3*(k-1) + i
            cols_dy[idx] = 3*(k-1) + j
            vals_dy[idx] = c[j] / det2
        end
        w[i1] = area / 3
        w[i2] = area / 3
        w[i3] = area / 3
    end
    dx = sparse(rows_dx, cols_dx, vals_dx, 3*N, 3*N)
    dy = sparse(rows_dy, cols_dy, vals_dy, 3*N, 3*N)
    return dx, dy, w
end

# Continuity-and-zero-Dirichlet subspace at level l on a 3N × 2 doubled-DOF
# corner mesh. Mirrors `MultiGridBarrier.continuous` but with 3-row blocks.
function _continuous_p1(x::Matrix{T}) where {T}
    n = size(x, 1)
    @assert n % 3 == 0
    N = n ÷ 3

    unique_xy, labels = _dedupe(x)
    n_v = size(unique_xy, 1)

    tri_conn = collect(transpose(reshape(labels, 3, N)))   # N × 3
    boundary = _find_boundary_corners(tri_conn)
    interior = setdiff(1:n_v, boundary)
    n_int    = length(interior)

    interior_pos = Dict{Int, Int}()
    for (j, ui) in enumerate(interior)
        interior_pos[ui] = j
    end

    rows = Int[]; cols = Int[]; vals = T[]
    sizehint!(rows, n); sizehint!(cols, n); sizehint!(vals, n)
    for i in 1:n
        ui = labels[i]
        if haskey(interior_pos, ui)
            push!(rows, i)
            push!(cols, interior_pos[ui])
            push!(vals, T(1))
        end
    end
    return sparse(rows, cols, vals, n, n_int)
end
